[project]
name = "monumental-swe-th2"
version = "0.1.0"
description = "Monumental take home assignment"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pyqt6>=6.11.0",
    "websockets>=17.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
